spring.application.name=01-EnterpriseIdentityAccessManagement

# PostgreSQL Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/EnterpriseIdentityAccessManagement
spring.datasource.username=postgres
spring.datasource.password=root
server.port=9090

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# JWT CONFIGURATION
# ==========================================

jwt.secret=YourVeryLongSecretKeyForEnterpriseIAMApplication123456789123456789

jwt.access-token-expiration=900000

jwt.refresh-token-expiration=604800000

logging.level.root=INFO
logging.level.com.techpalle=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=logs/IdentityAccessManagement.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs